project:
  type: website
  output-dir: docs
  # render:
  #   - "*.qmd"
  #   - "!Homework/CSSS508_HW1_*.qmd"
  #   - "!notes/*.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    grid: 
      sidebar-width: 300px
      body-width: 1000px
    fontsize: 1.1rem

website:
  reader-mode: true
  title: "CSSS 508"
  navbar:
    left:
      - syllabus.qmd
      - file: Lectures/lectures.qmd
        text: "Lectures"
      - file: Homework/homework.qmd
        text: "Homework"
  sidebar: 
    - title: "Lectures"
      style: "docked"
      contents: 
        - Lectures/lectures.qmd
        - file: Lectures/CSSS508_Lecture1.qmd
          text: "Lecture 1: Getting started"
        - file: Lectures/CSSS508_Lecture2.qmd
          text: "Lecture 2: Data viz"
        - file: Lectures/CSSS508_Lecture3.qmd
          text: "Lecture 3: Workflow"
        - file: Lectures/CSSS508_Lecture4.qmd
          text: "Lecture 4: Data wrangling"
        - file: Lectures/CSSS508_Lecture5.qmd
          text: "Lecture 5: Import, tidy, export"
        - file: Lectures/CSSS508_Lecture6.qmd
          text: "Lecture 6: Data structures and types"
        - file: Lectures/CSSS508_Lecture7.qmd
          text: "Lecture 7: Text data"
        - file: Lectures/CSSS508_Lecture8.qmd
          text: "Lecture 8: Writing functions"
        - file: Lectures/CSSS508_Lecture9.qmd
          text: "Lecture 9: Iteration"
        - file: Lectures/CSSS508_Lecture10.qmd
          text: "Lecture 10: Next steps"

    - title: "Homework"
      style: "docked"
      contents: 
        - Homework/homework.qmd
        - file: Homework/homework1.qmd
          text: "Homework 1"
        - file: Homework/homework2.qmd
          text: "Homework 2"
        - file: Homework/homework3.qmd
          text: "Homework 3"
        - file: Homework/homework4.qmd
          text: "Homework 4"
        - file: Homework/homework5.qmd
          text: "Homework 5"
        - file: Homework/homework6.qmd
          text: "Homework 6"
        - file: Homework/homework7.qmd
          text: "Homework 7"
        - file: Homework/homework8.qmd
          text: "Homework 8"
        - file: Homework/homework9.qmd
          text: "Homework 9"

